version: "3.7"

services:
  managedhost-app-1:
    build: 
      context: managed-host/alpine/app1
    restart: unless-stopped
    networks:
      - my-network
    environment:
      - SSH_ENABLE_ROOT=true
    volumes:
      - ./secrets/id_rsa_container.pub:/root/.ssh/authorized_keys
    ports:
      - "3000:3000"
      - "2223:2223"
  managedhost-app-2:
    build: 
      context: managed-host/alpine/app2
    restart: unless-stopped
    networks:
      - my-network
    environment:
      - SSH_ENABLE_ROOT=true
    volumes:
      - ./secrets/id_rsa_container.pub:/root/.ssh/authorized_keys
    ports:
      - "3001:3000"
      - "2224:2224"    
  managedhost-app-3:
    build: 
      context: managed-host/alpine/app3
    restart: unless-stopped
    networks:
      - my-network
    environment:
      - SSH_ENABLE_ROOT=true
    volumes:
      - ./secrets/id_rsa_container.pub:/root/.ssh/authorized_keys
    ports:
      - "3002:3000"
      - "2225:2225"

  load-balancer:
    build:
      context: managed-host/load-balancer
    restart: unless-stopped
    networks:
      - my-network
    environment:
      - SSH_ENABLE_ROOT=true
    volumes:
      - ./secrets/id_rsa_container.pub:/root/.ssh/authorized_keys
    ports:
      - "8081:8080"
      - "2226:2226"
      - "80:80"

    
networks:
  my-network:
    driver: bridge